import type { Hike } from "./types";

// Demo data used when Supabase is not configured. Replaced by real DB queries once connected.
export const demoHikes: Hike[] = [
  {
    id: "1",
    user_id: "demo",
    name: "Lac Blanc - Chamonix",
    date: "2025-08-15",
    distance_km: 12.4,
    elevation_m: 950,
    duration_min: 320,
    difficulty: "moderate",
    notes:
      "Vue incroyable sur le massif du Mont-Blanc. Sentier bien balisé, quelques passages raides avant le lac.",
    gpx_data: null,
    source: "manual",
    external_id: null,
    lat: 45.9767,
    lng: 6.8882,
    tags: ["lac", "sommet", "alpes"],
    created_at: "2025-08-15T18:00:00Z",
  },
  {
    id: "2",
    user_id: "demo",
    name: "GR20 - Étape Vizzavona",
    date: "2025-07-22",
    distance_km: 18.7,
    elevation_m: 1450,
    duration_min: 540,
    difficulty: "hard",
    notes:
      "Étape mythique du GR20. Départ tôt le matin pour éviter la chaleur. Cascade des Anglais magnifique.",
    gpx_data: null,
    source: "manual",
    external_id: null,
    lat: 42.1167,
    lng: 9.1167,
    tags: ["gr20", "corse", "montagne"],
    created_at: "2025-07-22T20:00:00Z",
  },
  {
    id: "3",
    user_id: "demo",
    name: "Tour des Lacs d'Ayous",
    date: "2025-09-03",
    distance_km: 14.2,
    elevation_m: 820,
    duration_min: 380,
    difficulty: "moderate",
    notes:
      "Boucle classique des Pyrénées. Reflet du Pic du Midi d'Ossau dans le lac Gentau au lever du soleil.",
    gpx_data: null,
    source: "manual",
    external_id: null,
    lat: 42.8431,
    lng: -0.4417,
    tags: ["lac", "boucle", "pyrénées"],
    created_at: "2025-09-03T17:00:00Z",
  },
  {
    id: "4",
    user_id: "demo",
    name: "Pic du Canigou",
    date: "2025-06-10",
    distance_km: 22.1,
    elevation_m: 1650,
    duration_min: 600,
    difficulty: "hard",
    notes: "Montée par le refuge des Cortalets. Neige résiduelle au sommet.",
    gpx_data: null,
    source: "strava",
    external_id: "strava_12345",
    lat: 42.5192,
    lng: 2.4567,
    tags: ["sommet", "pyrénées", "neige"],
    created_at: "2025-06-10T19:00:00Z",
  },
  {
    id: "5",
    user_id: "demo",
    name: "Sentier des Douaniers - Cap Fréhel",
    date: "2025-05-20",
    distance_km: 8.5,
    elevation_m: 180,
    duration_min: 150,
    difficulty: "easy",
    notes:
      "Balade côtière magnifique avec vue sur les falaises. Idéal pour une sortie famille.",
    gpx_data: null,
    source: "manual",
    external_id: null,
    lat: 48.6833,
    lng: -2.3333,
    tags: ["côte", "bretagne", "famille"],
    created_at: "2025-05-20T14:00:00Z",
  },
  {
    id: "6",
    user_id: "demo",
    name: "Aiguille du Midi - Arête",
    date: "2025-09-18",
    distance_km: 6.0,
    elevation_m: 1200,
    duration_min: 480,
    difficulty: "expert",
    notes: "Course d'alpinisme engagée. Crampons et piolet obligatoires.",
    gpx_data: null,
    source: "manual",
    external_id: null,
    lat: 45.8786,
    lng: 6.8872,
    tags: ["alpinisme", "alpes", "sommet"],
    created_at: "2025-09-18T16:00:00Z",
  },
];
